# Generated by Django 2.1.4 on 2018-12-15 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publiched_date',
            new_name='published_date',
        ),
    ]
